<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>Dialog</name>
    <message>
        <source>Email</source>
        <translation type="obsolete">邮箱</translation>
    </message>
    <message>
        <source>Password</source>
        <translation type="obsolete">密码</translation>
    </message>
</context>
<context>
    <name>LoginDialog</name>
    <message>
        <location filename="logindialog.ui" line="14"/>
        <source>Dialog</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="logindialog.ui" line="117"/>
        <source>Register</source>
        <translation type="unfinished">注册账号</translation>
    </message>
    <message>
        <location filename="logindialog.ui" line="149"/>
        <source>password</source>
        <translation type="unfinished">输入密码</translation>
    </message>
    <message>
        <location filename="logindialog.ui" line="156"/>
        <source>Email</source>
        <translation type="unfinished">邮箱</translation>
    </message>
    <message>
        <location filename="logindialog.ui" line="163"/>
        <source>Password</source>
        <translation type="unfinished">密码</translation>
    </message>
    <message>
        <location filename="logindialog.ui" line="187"/>
        <source>login</source>
        <translation type="unfinished">登  录</translation>
    </message>
    <message>
        <location filename="LoginDialog.cpp" line="27"/>
        <source>username or password could not be empty</source>
        <translation type="unfinished">账号和密码不能够为空</translation>
    </message>
    <message>
        <location filename="LoginDialog.cpp" line="31"/>
        <source>login failed</source>
        <translation type="unfinished">登录失败</translation>
    </message>
</context>
<context>
    <name>UiOneToOneRoom</name>
    <message>
        <location filename="OneToOneRoom.ui" line="14"/>
        <source>Dialog</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="OneToOneRoom.ui" line="62"/>
        <source>...</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>qtchatclient</name>
    <message>
        <location filename="qtchatclient.cpp" line="118"/>
        <source>Open Image File</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtchatclient.cpp" line="118"/>
        <source>Image Files (*.jpg;*.png;*.gif;*.jpeg)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtchatclient.cpp" line="146"/>
        <source>online</source>
        <translation type="unfinished">上线</translation>
    </message>
    <message>
        <location filename="qtchatclient.cpp" line="149"/>
        <source>offline</source>
        <translation type="unfinished">离线</translation>
    </message>
    <message>
        <location filename="qtchatclient.cpp" line="152"/>
        <source>restore</source>
        <translation type="unfinished">显示主面板</translation>
    </message>
    <message>
        <location filename="qtchatclient.cpp" line="155"/>
        <source>quit</source>
        <translation type="unfinished">退出</translation>
    </message>
</context>
<context>
    <name>qtchatclientClass</name>
    <message>
        <location filename="qtchatclient.ui" line="14"/>
        <source>qtchatclient</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtchatclient.ui" line="179"/>
        <source>&amp;Close</source>
        <translation type="unfinished">关闭(&amp;C)</translation>
    </message>
    <message>
        <location filename="qtchatclient.ui" line="198"/>
        <source>&amp;Send</source>
        <translation type="unfinished">发送(&amp;S)</translation>
    </message>
    <message>
        <source>关闭(&amp;C)</source>
        <translation type="obsolete">关闭(&amp;C)</translation>
    </message>
    <message>
        <source>发送(&amp;S)</source>
        <translation type="obsolete">发送(&amp;S</translation>
    </message>
</context>
<context>
    <name>weberror</name>
    <message>
        <location filename="weberror.cpp" line="45"/>
        <location filename="weberror.cpp" line="131"/>
        <source>No error</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="48"/>
        <source>The remote server refused the connection (the server is not accepting requests).</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="51"/>
        <source>The remote server closed the connection prematurely, before the entire reply was received and processed.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="54"/>
        <source>The remote host name was not found (invalid hostname).</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="57"/>
        <source>The connection to the remote server timed out.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="60"/>
        <source>The operation was canceled via calls to abort() or close() before it was finished.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="63"/>
        <source>The SSL/TLS handshake failed and the encrypted channel could not be established.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="66"/>
        <source>The connection was broken due to disconnection from the network, however the system has initiated roaming to another access point. The request should be resubmitted and will be processed as soon as the connection is re-established.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="69"/>
        <source>The connection to the proxy server was refused (the proxy server is not accepting requests).</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="72"/>
        <source>The proxy server closed the connection prematurely, before the entire reply was received and processed.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="75"/>
        <source>The proxy host name was not found (invalid proxy hostname).</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="78"/>
        <source>The connection to the proxy timed out or the proxy did not reply in time to the request sent.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="81"/>
        <source>The proxy requires authentication in order to honour the request but did not accept any credentials offered (if any).</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="84"/>
        <source>The access to the remote content was denied (similar to HTTP error 401).</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="87"/>
        <source>The operation requested on the remote content is not permitted.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="90"/>
        <source>The remote content was not found at the server (similar to HTTP error 404).</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="93"/>
        <source>The remote server requires authentication to serve the content but the credentials provided were not accepted (if any).</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="96"/>
        <source>The request needed to be sent again, but this failed for example because the upload data could not be read a second time.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="99"/>
        <source>The Network Access API cannot honor the request because the protocol is not known.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="102"/>
        <source>The requested operation is invalid for this protocol.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="105"/>
        <source>An unknown network-related error was detected.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="108"/>
        <source>An unknown proxy-related error was detected.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="111"/>
        <source>An unknown error related to the remote content was detected.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="114"/>
        <source>A breakdown in protocol was detected (parsing error, invalid or unexpected responses, etc.).</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="134"/>
        <source>The issuer certificate could not be found.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="137"/>
        <source>The certificate signature could not be decrypted.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="140"/>
        <source>The public key in the certificate could not be read.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="143"/>
        <source>The signature of the certificate is invalid.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="146"/>
        <source>The certificate is not yet valid.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="149"/>
        <source>The certificate has expired.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="152"/>
        <source>The certificate&apos;s notBefore field contains an invalid time.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="155"/>
        <source>The certificate&apos;s notAfter field contains an invalid time.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="158"/>
        <source>The certificate is self-signed, and untrusted.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="161"/>
        <source>The root certificate of the certificate chain is self-signed, and untrusted.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="164"/>
        <source>The issuer certificate of a locally looked up certificate could not be found.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="167"/>
        <source>No certificates could be verified.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="170"/>
        <source>One of the CA certificates is invalid.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="173"/>
        <source>The basicConstraints path length parameter has been exceeded</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="176"/>
        <source>The supplied certificate is unsuitable for this purpose.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="179"/>
        <source>The root CA certificate is not trusted for this purpose.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="182"/>
        <source>The root CA certificate is marked to reject the specified purpose.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="185"/>
        <source>The current candidate issuer certificate was rejected because its subject name did not match the issuer name of the current certificate.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="189"/>
        <source>The current candidate issuer certificate was rejected because its issuer name and serial number was present and did not match the authority key identifier of the current certificate.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="194"/>
        <source>The peer did not present any certificate.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="197"/>
        <source>The host name did not match any of the valid hosts for this certificate.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="201"/>
        <source>Unspecified error.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="204"/>
        <source>The peer presented a certificate that was revoked.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="207"/>
        <source>No SSL support.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="weberror.cpp" line="211"/>
        <source>The peer presented a certificate that was blacklisted.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
